// constante a modifier selon les pin utiliser
#define PIN_SUIVEUR_DE_LIGNE_DROIT A8
#define PIN_SUIVEUR_DE_LIGNE_MILLIEU A9 
#define PIN_SUIVEUR_DE_LIGNE_GAUCHE A10

#define PIN_CAMERA_RASPBERRY_PI A7

#define PIN_MOTEUR_SEL A6

// SONAR
#define PIN_SONAR_TRIG 2
#define PIN_SONAR_ECHO 3
#define PIN_SONAR_TRIG_2 4
#define PIN_SONAR_ECHO_2 5
#define PIN_SONAR_MAX_DIST 50
#define PIN_SONAR_MIN_DIST 5